# Generated by Django 4.1.2 on 2023-05-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('User_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_psd', models.TextField()),
                ('User_nickname', models.TextField()),
                ('User_status', models.TextField()),
            ],
            options={
                'db_table': 'Clients_table',
            },
        ),
    ]
