# Generated by Django 4.1.2 on 2023-05-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersgroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='User_nickname',
            field=models.TextField(null=True),
        ),
    ]
