# Generated by Django 4.1.2 on 2023-04-20 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basicinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Unique_id', models.TextField()),
                ('Product_name', models.TextField()),
                ('Brand_name', models.TextField()),
                ('Category', models.TextField()),
                ('Selling_price', models.TextField()),
                ('Image', models.TextField()),
                ('Amazon_seller', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model_number', models.TextField()),
                ('About_product', models.TextField()),
                ('Product_specification', models.TextField()),
                ('Technical_details', models.TextField()),
                ('Shipping_weight', models.TextField()),
                ('Product_dimensions', models.TextField()),
                ('Unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='shopping.basicinfo')),
            ],
        ),
    ]
