# Generated by Django 4.1.2 on 2023-04-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
