# Generated by Django 4.1.2 on 2023-04-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_detail_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='Brand_name',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='Category',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='About_product',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Product_dimensions',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Product_specification',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Shipping_weight',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Technical_details',
            field=models.TextField(default='None'),
        ),
    ]
