# Generated by Django 4.1.2 on 2023-04-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_alter_basicinfo_brand_name_alter_basicinfo_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='Brand_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='Category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='About_product',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Product_dimensions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Product_specification',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Shipping_weight',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Technical_details',
            field=models.TextField(),
        ),
    ]
